description: >
  This command build docker image

steps:
  - setup_remote_docker:
      docker_layer_caching: true
  - run:
      name: Build docker image
      command: << include(scripts/build.sh) >>
